INSERT INTO product VALUES (1, 'tt', 'ddd', 200.0, 'hm', 's','this is a description');
INSERT INTO product VALUES (2, 'tt', 'ddd', 300.0, 'hm', 's','this is a description');
INSERT INTO product VALUES (3, 'tt', 'ddd', 800.0, 'hm', 's','this is a description');
INSERT INTO product VALUES (4, 'tt', 'ddd', 700.0, 'hm', 's','this is a description');
INSERT INTO product VALUES (5, 'tt', 'ddd', 600.0, 'hm', 's','this is a description');
INSERT INTO product VALUES (6, 'tt', 'ddd', 200.0, 'hm', 's','this is a description');
INSERT INTO product VALUES (7, 'tt', 'ddd', 400.0, 'hm', 's','this is a description');
INSERT INTO product VALUES (8, 'tt', 'ddd', 100.0, 'hm', 's','this is a description');
INSERT INTO product VALUES (9, 'tt', 'ddd', 500.05, 'hm', 's','this is a description');
INSERT INTO product VALUES (10, 'tt', 'ddd', 600.0, 'hm', 's','this is a description');
INSERT INTO product VALUES (11, 'tt', 'ddd', 900.0, 'hm', 's','this is a description');
INSERT INTO product VALUES (12, 'tt', 'ddd',10200.0, 'hm', 's','this is a description');
INSERT INTO product VALUES (13, 'tt', 'ddd', 6600.0, 'hm', 's','this is a description');
INSERT INTO product VALUES (14, 'tt', 'ddd', 330.0, 'hm', 's','this is a description');
INSERT INTO product VALUES (15, 'tt', 'ddd', 890.0, 'hm', 's','this is a description');
INSERT INTO product VALUES (16, 'tt', 'ddd', 210.0, 'hm', 's','this is a description');
